# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datamanager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61tamanager.proto\"\x91\x01\n\rServiceConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x05\x12\x17\n\x0f\x61lerting_window\x18\x04 \x01(\x05\x12\x19\n\x11\x61llowed_resp_time\x18\x05 \x01(\x05\x12\x0e\n\x06\x65mail1\x18\x06 \x01(\t\x12\x0e\n\x06\x65mail2\x18\x07 \x01(\t\"\x1d\n\x0bResponseMsg\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1b\n\x0bServiceName\x12\x0c\n\x04name\x18\x01 \x01(\t2;\n\x0b\x44\x61taManager\x12,\n\x0c\x43hangeConfig\x12\x0e.ServiceConfig\x1a\x0c.ResponseMsgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datamanager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICECONFIG._serialized_start=22
  _SERVICECONFIG._serialized_end=167
  _RESPONSEMSG._serialized_start=169
  _RESPONSEMSG._serialized_end=198
  _SERVICENAME._serialized_start=200
  _SERVICENAME._serialized_end=227
  _DATAMANAGER._serialized_start=229
  _DATAMANAGER._serialized_end=288
# @@protoc_insertion_point(module_scope)
