name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      DATAMANAGER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DATAMANAGER_APP_NAME }}:latest
      DATAMANAGER_API_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DATAMANAGER_API_NAME }}:latest
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dataretriever pubsub topic
        run: chmod +x scripts/create-topic-nofail.sh && ./scripts/create-topic-nofail.sh ${{ secrets.GCP_DATAMANAGER_TOPIC }}
        shell: bash

      - name: Create dataretriever pubsub subscription
        run: chmod +x scripts/create-sub-nofail.sh && ./scripts/create-sub-nofail.sh \
             ${{ secrets.GCP_DATARETRIEVER_SUBSCRIPTION }} ${{ secrets.GCP_DATAMANAGER_TOPIC }} ${{ secrets.GCP_DR_RECEIVER_ENDPOINT }}
        shell: bash

      - name: Build datamanager docker
        run: chmod +x scripts/build-docker.sh && ./scripts/build-docker.sh ${{ secrets.GCP_DATAMANAGER_APP_NAME }} $DATAMANAGER_IMAGE_NAME
        shell: bash

      - name: Build datamanager-api docker
        run: chmod +x scripts/build-docker.sh && ./scripts/build-docker.sh ${{ secrets.GCP_DATAMANAGER_API_NAME }} $DATAMANAGER_API_IMAGE_NAME
        shell: bash

      - name: Deploy datamanager docker
        run: chmod +x scripts/deploy.sh && ./scripts/deploy.sh ${{ secrets.GCP_DATAMANAGER_APP_NAME }} $DATAMANAGER_IMAGE_NAME ${{ secrets.CLOUDSQL_INSTANCE }}
        shell: bash

      - name: Deploy datamanager-api docker
        run: chmod +x scripts/deploy-api.sh && ./scripts/deploy-api.sh ${{ secrets.GCP_DATAMANAGER_API_NAME }} $DATAMANAGER_API_IMAGE_NAME
        shell: bash